# Generated by Django 4.2.6 on 2023-11-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_time', models.DateTimeField()),
                ('bid_title', models.CharField(max_length=255)),
                ('bid_text', models.CharField(max_length=255)),
                ('bid_web', models.CharField(max_length=255)),
            ],
        ),
    ]
