# Generated by Django 4.2.6 on 2023-11-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_title', models.CharField(max_length=255)),
                ('bid_time', models.DateTimeField()),
                ('bid_text', models.CharField(max_length=255)),
                ('bid_web', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
