# Generated by Django 4.2.6 on 2023-11-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_bidding1_bid_time_alter_bidding2_bid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding1',
            name='bid_text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='bidding2',
            name='bid_text',
            field=models.CharField(max_length=10000),
        ),
    ]
