# Generated by Django 4.2.6 on 2023-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_bidding1_bid_text_alter_bidding2_bid_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_title', models.CharField(max_length=255)),
                ('bid_time', models.CharField(max_length=255)),
                ('bid_text', models.CharField(max_length=100000)),
                ('bid_web', models.CharField(max_length=255)),
                ('bid_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='bidding1',
        ),
        migrations.DeleteModel(
            name='bidding2',
        ),
    ]
