# Generated by Django 2.2.10 on 2024-03-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_bidding_bid_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
